name: Analyze & Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-analysis:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze

  e2e-test:
    runs-on: macos-latest
    timeout-minutes: 45
    strategy:
      matrix:
        api-level: [29, 30, 31, 32]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis 
          script: | 
           flutter drive --target=test_driver/app.dart --driver=test_driver/key_new.dart
           flutter drive --target=test_driver/app.dart --driver=test_driver/key_imported.dart
      # - name: Upload screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: screenshot-${{ matrix.api-level }}
      #     path: fail-screenshots/${{ matrix.api-level }}/
      #     retention-days: 5