name: Analyze & Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-analysis:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
      # run static analys code
    - run: flutter analyze

  e2e-test-29-30:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [29, 30]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: | 
           flutter drive --target=test_driver/app.dart --driver=test_driver/key_new.dart --screenshot=fail-screenshots/
           flutter drive --target=test_driver/app.dart --driver=test_driver/key_imported.dart --screenshot=fail-screenshots/
      - name: Upload screenshots
            if: always()
            uses: actions/upload-artifact@v3
            with:
              name: screenshot_29_30
              path: fail-screenshots/
              retention-days: 5

  e2e-test-31:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [31]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: arm64-v8a
          script: | 
           flutter drive --target=test_driver/app.dart --driver=test_driver/key_new.dart --screenshot=fail-screenshots/
           flutter drive --target=test_driver/app.dart --driver=test_driver/key_imported.dart --screenshot=fail-screenshots/
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot_31
          path: fail-screenshots/
          retention-days: 5
